server:
  port: 9509
spring:
  profiles:
    active: dev
  application:
    name: evan-admin-pay
  rabbitmq:
    host: localhost
    username: rabbitmq
    password: rabbitmq
    port: 5672
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    stream:
      bindings:
        delayCloseOrder:
          consumer:
            concurrency: 4
            max-attempts: 1
          content-type: application/json
          destination: order-service_topic
          group: order-service_delay-close-order_cg
        orderOutput:
          content-type: application/json
          destination: order-service_topic
          group: order-service_general-send_pg
        payResultNotify:
          consumer:
            concurrency: 4
            max-attempts: 1
          content-type: application/json
          destination: pay-service_topic
          group: order-service_pay-result-notify_cg
      rocketmq:
        bindings:
          delayCloseOrder:
            consumer:
              delay-level-when-next-consume: -1
              tags: order-service_delay-close-order_tag
          orderOutput:
            producer:
              sync: true
          payResultNotify:
            consumer:
              delay-level-when-next-consume: -1
              tags: pay-service_pay-result-notify_tag
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
  datasource:
    name: defaultDataSource
    url: jdbc:mysql://localhost:3306/pay
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    database: 0
    port: 6379
    host: localhost
    password: root
    cache-minute: 1
management:
  endpoints:
    web:
      exposure:
        include: "*"

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #开启sql日志
  global-config:
    banner: false
    db-config:
      id-type: auto
      table-prefix: tb_wang_
      logic-delete-field: deleted
      logic-not-delete-value: 0
      logic-delete-value: 1