insert into MY_TABLE (id, url)
values  (1, '/order/hello'),
        (2, '/order/project/userProjectList'),
        (3, '/user/menu/list'),
        (4, '/order/project/list'),
        (5, '/order/feign'),
        (6, '/pay/pay'),
        (7, '/order/user/currentUser'),
        (8, '/pay/feign'),
        (9, '/user/menu/list'),
        (10, '/auth/oauth/logout'),
        (11, '/order/user/getPermCode'),
        (12, '/order/user/getMenuList'),
        (13, '/user/menu/listPage'),
        (14, '/user/system/getDeptList'),
        (15, '/user/system/getAccountList');