insert into MY_TABLE (id, url)
values  (1, '/order/hello'),
        (2, '/order/project/userProjectList'),
        (3, '/business-menu/menu/list'),
        (4, '/order/project/list'),
        (5, '/order/feign'),
        (6, '/business-demo/business-demo'),
        (7, '/order/user/currentUser'),
        (8, '/business-demo/feign'),
        (9, '/business-menu/menu/list'),
        (10, '/auth/oauth/logout'),
        (11, '/order/user/getPermCode'),
        (12, '/order/user/feignGetMenuList'),
        (13, '/business-menu/menu/listPage'),
        (14, '/business-menu/system/getDeptList'),
        (15, '/business-menu/system/getAccountList');