insert into MY_TABLE (id, url)
values  (1, '/business-resource/hello'),
        (2, '/business-resource/project/userProjectList'),
        (3, '/business-menu/menu/list'),
        (4, '/business-resource/project/list'),
        (5, '/business-resource/feign'),
        (6, '/business-demo/business-demo'),
        (7, '/business-resource/user/currentUser'),
        (8, '/business-demo/feign'),
        (9, '/business-menu/menu/list'),
        (10, '/auth/oauth/logout'),
        (11, '/business-resource/user/getPermCode'),
        (12, '/business-resource/user/feignGetMenuList'),
        (13, '/business-menu/menu/listPage'),
        (14, '/business-menu/system/getDeptList'),
        (15, '/business-menu/system/getAccountList');